server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: 100MB
    max-http-form-post-size: 100MB
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elfinder?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
  # 出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
    throw-exception-if-no-handler-found: true
#    view:
#      prefix: /
#      suffix: .html
    # 不要为工程中的资源文件建立映射
  freemarker:
    template-loader-path:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  #  resources:
#    add-mappings: false
#  resources:
#    static-locations: classpath:static/classpath:/templates/
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB
  redis:
    host: 192.167.200.129
    port: 6379
    lettuce:
      pool:
        max-wait: -1ms
        max-active: 8
        min-idle: 0
        max-idle: 8
#    password: 888666312

file-manager:
  thumbnail:
    width: 80 # 缩略图宽
  volumes:
    - Node:
      source: fileSystem # 暂时只支持本地文件系统
      alias: files # 目录别名
      path: /D:/CR # 映射目录
      isDefault: true # 是否默认打开
      locale:
      constraint:
        locked: false # 文件夹是否锁定
        readable: true # 是否可读
        writable: true # 是否可写
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: localhost
  cookieMaxAge: -1
  tokenValidityInSeconds: 360000
encrypt:
  key-store:
    location: classpath:/changgou.jks
    secret: changgou
    alias: changgou
    password: changgou
#logging:
#  level:
#    root: debug









